### ISSUE TITLE
error in npm run develop

### ISSUE THREAD

**Issue by darth16Vader** [cobidev/gatsby-simplefolio#43]
USER@LAPTOP-A8RM9C82 MINGW64 ~/Downloads/gatsby-simplefolio-master
$ npm run develop

> gatsby-starter-hello-world@0.1.0 develop
> gatsby develop

success open and validate gatsby-configs - 0.067s

 ERROR 

Error in "C:\Users\USER\Downloads\gatsby-simplefolio-master\node_modules\gatsby-transformer-sharp\gatsby-node.js":
Something went wrong installing the "sharp" module

Cannot find module '../build/Release/sharp.node'
Require stack:
- C:\Users\USER\Downloads\gatsby-simplefolio-master\node_modules\sharp\lib\constructor.js
- C:\Users\USER\Downloads\gatsby-simplefolio-master\node_modules\sharp\lib\index.js
- C:\Users\USER\Downloads\gatsby-simplefolio-master\node_modules\gatsby-plugin-sharp\safe-sharp.js
- C:\Users\USER\Downloads\gatsby-simplefolio-master\node_modules\gatsby-plugin-sharp\index.js
- C:\Users\USER\Downloads\gatsby-simplefolio-master\node_modules\gatsby-transformer-sharp\customize-schema.js
- C:\Users\USER\Downloads\gatsby-simplefolio-master\node_modules\gatsby-transformer-sharp\gatsby-node.js
- C:\Users\USER\Downloads\gatsby-simplefolio-master\node_modules\gatsby\dist\bootstrap\resolve-module-exports.js
- C:\Users\USER\Downloads\gatsby-simplefolio-master\node_modules\gatsby\dist\bootstrap\load-plugins\validate.js
- C:\Users\USER\Downloads\gatsby-simplefolio-master\node_modules\gatsby\dist\bootstrap\load-plugins\load.js
- C:\Users\USER\Downloads\gatsby-simplefolio-master\node_modules\gatsby\dist\bootstrap\load-plugins\index.js
- C:\Users\USER\Downloads\gatsby-simplefolio-master\node_modules\gatsby\dist\services\initialize.js
- C:\Users\USER\Downloads\gatsby-simplefolio-master\node_modules\gatsby\dist\services\index.js
- C:\Users\USER\Downloads\gatsby-simplefolio-master\node_modules\gatsby\dist\bootstrap\index.js
- C:\Users\USER\Downloads\gatsby-simplefolio-master\node_modules\gatsby\dist\commands\develop-process.js
- C:\Users\USER\Downloads\gatsby-simplefolio-master\.cache\tmp-18492-Ui67KyqyqIVV

- Run "npm rebuild --verbose sharp" and look for errors
- Consult the installation documentation at https://sharp.pixelplumbing.com/install
- Search for this error at https://github.com/lovell/sharp/issues

  Error: Something went wrong installing the "sharp" module
  Cannot find module '../build/Release/sharp.node'
  Require stack:
  - C:\Users\USER\Downloads\gatsby-simplefolio-master\node_modules\sharp\lib\constructor.js
  - C:\Users\USER\Downloads\gatsby-simplefolio-master\node_modules\sharp\lib\index.js
  - C:\Users\USER\Downloads\gatsby-simplefolio-master\node_modules\gatsby-plugin-sharp\safe-sharp.js
  - C:\Users\USER\Downloads\gatsby-simplefolio-master\node_modules\gatsby-plugin-sharp\index.js
  - C:\Users\USER\Downloads\gatsby-simplefolio-master\node_modules\gatsby-transformer-sharp\customize-schema.js
  - C:\Users\USER\Downloads\gatsby-simplefolio-master\node_modules\gatsby-transformer-sharp\gatsby-node.js
  - C:\Users\USER\Downloads\gatsby-simplefolio-master\node_modules\gatsby\dist\bootstrap\resolve-module-exports.js
  - C:\Users\USER\Downloads\gatsby-simplefolio-master\node_modules\gatsby\dist\bootstrap\load-plugins\validate.js
  - C:\Users\USER\Downloads\gatsby-simplefolio-master\node_modules\gatsby\dist\bootstrap\load-plugins\load.js
  - C:\Users\USER\Downloads\gatsby-simplefolio-master\node_modules\gatsby\dist\bootstrap\load-plugins\index.js
  - C:\Users\USER\Downloads\gatsby-simplefolio-master\node_modules\gatsby\dist\services\initialize.js
  - C:\Users\USER\Downloads\gatsby-simplefolio-master\node_modules\gatsby\dist\services\index.js
  - C:\Users\USER\Downloads\gatsby-simplefolio-master\node_modules\gatsby\dist\bootstrap\index.js
  - C:\Users\USER\Downloads\gatsby-simplefolio-master\node_modules\gatsby\dist\commands\develop-process.js
  - C:\Users\USER\Downloads\gatsby-simplefolio-master\.cache\tmp-18492-Ui67KyqyqIVV
  - Run "npm rebuild --verbose sharp" and look for errors
  - Consult the installation documentation at https://sharp.pixelplumbing.com/install
  - Search for this error at https://github.com/lovell/sharp/issues

  - constructor.js:34 Object.<anonymous>
    [gatsby-simplefolio-master]/[sharp]/lib/constructor.js:34:9

  - v8-compile-cache.js:178 Module._compile
    [gatsby-simplefolio-master]/[gatsby]/[v8-compile-cache]/v8-compile-cache.js:178:30

  - loader:1131 Object.Module._extensions..js
    node:internal/modules/cjs/loader:1131:10

  - loader:967 Module.load
    node:internal/modules/cjs/loader:967:32

  - loader:807 Function.Module._load
    node:internal/modules/cjs/loader:807:14

  - loader:991 Module.require
    node:internal/modules/cjs/loader:991:19

  - v8-compile-cache.js:159 require
    [gatsby-simplefolio-master]/[gatsby]/[v8-compile-cache]/v8-compile-cache.js:159:20

  - index.js:3 Object.<anonymous>
    [gatsby-simplefolio-master]/[sharp]/lib/index.js:3:15

  - v8-compile-cache.js:178 Module._compile
    [gatsby-simplefolio-master]/[gatsby]/[v8-compile-cache]/v8-compile-cache.js:178:30

  - loader:1131 Object.Module._extensions..js
    node:internal/modules/cjs/loader:1131:10

  - loader:967 Module.load
    node:internal/modules/cjs/loader:967:32

  - loader:807 Function.Module._load
    node:internal/modules/cjs/loader:807:14

  - loader:991 Module.require
    node:internal/modules/cjs/loader:991:19

  - v8-compile-cache.js:159 require
    [gatsby-simplefolio-master]/[gatsby]/[v8-compile-cache]/v8-compile-cache.js:159:20

  - safe-sharp.js:127 Object.<anonymous>
    [gatsby-simplefolio-master]/[gatsby-plugin-sharp]/safe-sharp.js:127:11

  - v8-compile-cache.js:178 Module._compile
    [gatsby-simplefolio-master]/[gatsby]/[v8-compile-cache]/v8-compile-cache.js:178:30

not finished load plugins - 1.291s
npm ERR! code 1
npm ERR! path C:\Users\USER\Downloads\gatsby-simplefolio-master
npm ERR! command failed
npm ERR! command C:\WINDOWS\system32\cmd.exe /d /s /c "gatsby develop"

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\USER\AppData\Local\npm-cache\_logs\2021-01-15T06_15_07_200Z-debug.log

USER@LAPTOP-A8RM9C82 MINGW64 ~/Downloads/gatsby-simplefolio-master
$ npm start

> gatsby-starter-hello-world@0.1.0 start
> npm run develop

> gatsby-starter-hello-world@0.1.0 develop
> gatsby develop

success open and validate gatsby-configs - 0.034s

 ERROR 

Error in "C:\Users\USER\Downloads\gatsby-simplefolio-master\node_modules\gatsby-transformer-sharp\gatsby-node.js":
Something went wrong installing the "sharp" module

Cannot find module '../build/Release/sharp.node'
Require stack:
- C:\Users\USER\Downloads\gatsby-simplefolio-master\node_modules\sharp\lib\constructor.js
- C:\Users\USER\Downloads\gatsby-simplefolio-master\node_modules\sharp\lib\index.js
- C:\Users\USER\Downloads\gatsby-simplefolio-master\node_modules\gatsby-plugin-sharp\safe-sharp.js
- C:\Users\USER\Downloads\gatsby-simplefolio-master\node_modules\gatsby-plugin-sharp\index.js
- C:\Users\USER\Downloads\gatsby-simplefolio-master\node_modules\gatsby-transformer-sharp\customize-schema.js
- C:\Users\USER\Downloads\gatsby-simplefolio-master\node_modules\gatsby-transformer-sharp\gatsby-node.js
- C:\Users\USER\Downloads\gatsby-simplefolio-master\node_modules\gatsby\dist\bootstrap\resolve-module-exports.js
- C:\Users\USER\Downloads\gatsby-simplefolio-master\node_modules\gatsby\dist\bootstrap\load-plugins\validate.js
- C:\Users\USER\Downloads\gatsby-simplefolio-master\node_modules\gatsby\dist\bootstrap\load-plugins\load.js
- C:\Users\USER\Downloads\gatsby-simplefolio-master\node_modules\gatsby\dist\bootstrap\load-plugins\index.js
- C:\Users\USER\Downloads\gatsby-simplefolio-master\node_modules\gatsby\dist\services\initialize.js
- C:\Users\USER\Downloads\gatsby-simplefolio-master\node_modules\gatsby\dist\services\index.js
- C:\Users\USER\Downloads\gatsby-simplefolio-master\node_modules\gatsby\dist\bootstrap\index.js
- C:\Users\USER\Downloads\gatsby-simplefolio-master\node_modules\gatsby\dist\commands\develop-process.js
- C:\Users\USER\Downloads\gatsby-simplefolio-master\.cache\tmp-10784-Hy8ZaQyNfCfG

- Run "npm rebuild --verbose sharp" and look for errors
- Consult the installation documentation at https://sharp.pixelplumbing.com/install
- Search for this error at https://github.com/lovell/sharp/issues

  Error: Something went wrong installing the "sharp" module
  Cannot find module '../build/Release/sharp.node'
  Require stack:
  - C:\Users\USER\Downloads\gatsby-simplefolio-master\node_modules\sharp\lib\constructor.js
  - C:\Users\USER\Downloads\gatsby-simplefolio-master\node_modules\sharp\lib\index.js
  - C:\Users\USER\Downloads\gatsby-simplefolio-master\node_modules\gatsby-plugin-sharp\safe-sharp.js
  - C:\Users\USER\Downloads\gatsby-simplefolio-master\node_modules\gatsby-plugin-sharp\index.js
  - C:\Users\USER\Downloads\gatsby-simplefolio-master\node_modules\gatsby-transformer-sharp\customize-schema.js
  - C:\Users\USER\Downloads\gatsby-simplefolio-master\node_modules\gatsby-transformer-sharp\gatsby-node.js
  - C:\Users\USER\Downloads\gatsby-simplefolio-master\node_modules\gatsby\dist\bootstrap\resolve-module-exports.js
  - C:\Users\USER\Downloads\gatsby-simplefolio-master\node_modules\gatsby\dist\bootstrap\load-plugins\validate.js
  - C:\Users\USER\Downloads\gatsby-simplefolio-master\node_modules\gatsby\dist\bootstrap\load-plugins\load.js
  - C:\Users\USER\Downloads\gatsby-simplefolio-master\node_modules\gatsby\dist\bootstrap\load-plugins\index.js
  - C:\Users\USER\Downloads\gatsby-simplefolio-master\node_modules\gatsby\dist\services\initialize.js
  - C:\Users\USER\Downloads\gatsby-simplefolio-master\node_modules\gatsby\dist\services\index.js
  - C:\Users\USER\Downloads\gatsby-simplefolio-master\node_modules\gatsby\dist\bootstrap\index.js
  - C:\Users\USER\Downloads\gatsby-simplefolio-master\node_modules\gatsby\dist\commands\develop-process.js
  - C:\Users\USER\Downloads\gatsby-simplefolio-master\.cache\tmp-10784-Hy8ZaQyNfCfG
  - Run "npm rebuild --verbose sharp" and look for errors
  - Consult the installation documentation at https://sharp.pixelplumbing.com/install
  - Search for this error at https://github.com/lovell/sharp/issues

  - constructor.js:34 Object.<anonymous>
    [gatsby-simplefolio-master]/[sharp]/lib/constructor.js:34:9

  - v8-compile-cache.js:178 Module._compile
    [gatsby-simplefolio-master]/[gatsby]/[v8-compile-cache]/v8-compile-cache.js:178:30

  - loader:1131 Object.Module._extensions..js
    node:internal/modules/cjs/loader:1131:10

  - loader:967 Module.load
    node:internal/modules/cjs/loader:967:32

  - loader:807 Function.Module._load
    node:internal/modules/cjs/loader:807:14

  - loader:991 Module.require
    node:internal/modules/cjs/loader:991:19

  - v8-compile-cache.js:159 require
    [gatsby-simplefolio-master]/[gatsby]/[v8-compile-cache]/v8-compile-cache.js:159:20

  - index.js:3 Object.<anonymous>
    [gatsby-simplefolio-master]/[sharp]/lib/index.js:3:15

  - v8-compile-cache.js:178 Module._compile
    [gatsby-simplefolio-master]/[gatsby]/[v8-compile-cache]/v8-compile-cache.js:178:30

  - loader:1131 Object.Module._extensions..js
    node:internal/modules/cjs/loader:1131:10

  - loader:967 Module.load
    node:internal/modules/cjs/loader:967:32

  - loader:807 Function.Module._load
    node:internal/modules/cjs/loader:807:14

  - loader:991 Module.require
    node:internal/modules/cjs/loader:991:19

  - v8-compile-cache.js:159 require
    [gatsby-simplefolio-master]/[gatsby]/[v8-compile-cache]/v8-compile-cache.js:159:20

  - safe-sharp.js:127 Object.<anonymous>
    [gatsby-simplefolio-master]/[gatsby-plugin-sharp]/safe-sharp.js:127:11

  - v8-compile-cache.js:178 Module._compile
    [gatsby-simplefolio-master]/[gatsby]/[v8-compile-cache]/v8-compile-cache.js:178:30

not finished load plugins - 0.272s
npm ERR! code 1
npm ERR! path C:\Users\USER\Downloads\gatsby-simplefolio-master
npm ERR! command failed
npm ERR! command C:\WINDOWS\system32\cmd.exe /d /s /c "gatsby develop"

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\USER\AppData\Local\npm-cache\_logs\2021-01-15T06_16_10_617Z-debug.log
npm ERR! code 1
npm ERR! path C:\Users\USER\Downloads\gatsby-simplefolio-master
npm ERR! command failed
npm ERR! command C:\WINDOWS\system32\cmd.exe /d /s /c "npm run develop"

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\USER\AppData\Local\npm-cache\_logs\2021-01-15T06_16_10_954Z-debug.log

USER@LAPTOP-A8RM9C82 MINGW64 ~/Downloads/gatsby-simplefolio-master
$ npm rebuild --verbose sharp
npm verb cli [
npm verb cli   'C:\\Program Files\\nodejs\\node.exe',
npm verb cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
npm verb cli   'rebuild',
npm verb cli   '--verbose',
npm verb cli   'sharp'
npm verb cli ]
npm info using npm@7.0.8
npm info using node@v15.2.1
npm timing config:load:defaults Completed in 1ms
npm timing config:load:file:C:\Program Files\nodejs\node_modules\npm\npmrc Completed in 1ms
npm timing config:load:builtin Completed in 1ms
npm timing config:load:cli Completed in 2ms
npm timing config:load:env Completed in 0ms
npm timing config:load:file:C:\Users\USER\Downloads\gatsby-simplefolio-master\.npmrc Completed in 0ms
npm timing config:load:project Completed in 1ms
npm timing config:load:file:C:\Users\USER\.npmrc Completed in 0ms
npm timing config:load:user Completed in 0ms
npm timing config:load:file:C:\Users\USER\AppData\Roaming\npm\etc\npmrc Completed in 0ms
npm timing config:load:global Completed in 0ms
npm timing config:load:cafile Completed in 1ms
npm timing config:load:validate Completed in 0ms
npm timing config:load:setUserAgent Completed in 0ms
npm timing config:load:setEnvs Completed in 1ms
npm timing config:load Completed in 8ms
npm verb npm-session 94562c49b048a6d1
npm timing npm:load Completed in 64ms
npm timing arborist:ctor Completed in 1ms
npm timing arborist:ctor Completed in 0ms
npm timing build:queue Completed in 3ms
npm info run sharp@0.25.4 install node_modules/sharp (node install/libvips && node install/dll-copy && prebuild-install --runtime=napi) || (node-gyp rebuild && node install/dll-copy)
npm info run sharp@0.25.4 install { code: 1, signal: null }
npm timing command:rebuild Completed in 2349ms
npm verb stack Error: command failed
npm verb stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\@npmcli\promise-spawn\index.js:64:27)
npm verb stack     at ChildProcess.emit (node:events:329:20)
npm verb stack     at maybeClose (node:internal/child_process:1055:16)
npm verb stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:288:5)
npm verb pkgid sharp@0.25.4
npm verb cwd C:\Users\USER\Downloads\gatsby-simplefolio-master
npm verb Windows_NT 10.0.19042
npm verb argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "rebuild" "--verbose" "sharp"
npm verb node v15.2.1
npm verb npm  v7.0.8
npm ERR! code 1
npm ERR! path C:\Users\USER\Downloads\gatsby-simplefolio-master\node_modules\sharp
npm ERR! command failed
npm ERR! command C:\WINDOWS\system32\cmd.exe /d /s /c "(node install/libvips && node install/dll-copy && prebuild-install --runtime=napi) || (node-gyp rebuild && node install/dll-copy)"
npm ERR! info sharp Using existing vendored libvips v8.9.1
npm ERR! info sharp Creating C:\Users\USER\Downloads\gatsby-simplefolio-master\node_modules\sharp\build\Release
npm ERR! info sharp Copying DLLs from C:\Users\USER\Downloads\gatsby-simplefolio-master\node_modules\sharp\vendor\lib to C:\Users\USER\Downloads\gatsby-simplefolio-master\node_modules\sharp\build\Release
npm ERR! prebuild-install info begin Prebuild-install version 5.3.5
npm ERR! prebuild-install info install installing standalone, skipping download.
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp verb cli [
npm ERR! gyp verb cli   'C:\\Program Files\\nodejs\\node.exe',
npm ERR! gyp verb cli   'C:\\Users\\USER\\Downloads\\gatsby-simplefolio-master\\node_modules\\node-gyp\\bin\\node-gyp.js',
npm ERR! gyp verb cli   'rebuild'
npm ERR! gyp verb cli ]
npm ERR! gyp info using node-gyp@3.8.0
npm ERR! gyp info using node@15.2.1 | win32 | x64
npm ERR! gyp verb command rebuild []
npm ERR! gyp verb command clean []
npm ERR! gyp verb clean removing "build" directory
npm ERR! gyp verb command configure []
npm ERR! gyp verb check python checking for Python executable "python2" in the PATH
npm ERR! gyp verb `which` failed Error: not found: python2
npm ERR! gyp verb `which` failed     at getNotFoundError (C:\Users\USER\Downloads\gatsby-simplefolio-master\node_modules\node-gyp\node_modules\which\which.js:13:12)
npm ERR! gyp verb `which` failed     at F (C:\Users\USER\Downloads\gatsby-simplefolio-master\node_modules\node-gyp\node_modules\which\which.js:68:19)
npm ERR! gyp verb `which` failed     at E (C:\Users\USER\Downloads\gatsby-simplefolio-master\node_modules\node-gyp\node_modules\which\which.js:80:29)
npm ERR! gyp verb `which` failed     at C:\Users\USER\Downloads\gatsby-simplefolio-master\node_modules\node-gyp\node_modules\which\which.js:89:16
npm ERR! gyp verb `which` failed     at C:\Users\USER\Downloads\gatsby-simplefolio-master\node_modules\isexe\index.js:42:5
npm ERR! gyp verb `which` failed     at C:\Users\USER\Downloads\gatsby-simplefolio-master\node_modules\isexe\windows.js:36:5
npm ERR! gyp verb `which` failed     at FSReqCallback.oncomplete (node:fs:191:21)
npm ERR! gyp verb `which` failed  python2 Error: not found: python2
npm ERR! gyp verb `which` failed     at getNotFoundError (C:\Users\USER\Downloads\gatsby-simplefolio-master\node_modules\node-gyp\node_modules\which\which.js:13:12)
npm ERR! gyp verb `which` failed     at F (C:\Users\USER\Downloads\gatsby-simplefolio-master\node_modules\node-gyp\node_modules\which\which.js:68:19)
npm ERR! gyp verb `which` failed     at E (C:\Users\USER\Downloads\gatsby-simplefolio-master\node_modules\node-gyp\node_modules\which\which.js:80:29)
npm ERR! gyp verb `which` failed     at C:\Users\USER\Downloads\gatsby-simplefolio-master\node_modules\node-gyp\node_modules\which\which.js:89:16
npm ERR! gyp verb `which` failed     at C:\Users\USER\Downloads\gatsby-simplefolio-master\node_modules\isexe\index.js:42:5
npm ERR! gyp verb `which` failed     at C:\Users\USER\Downloads\gatsby-simplefolio-master\node_modules\isexe\windows.js:36:5
npm ERR! gyp verb `which` failed     at FSReqCallback.oncomplete (node:fs:191:21) {
npm ERR! gyp verb `which` failed   code: 'ENOENT'
npm ERR! gyp verb `which` failed }
npm ERR! gyp verb check python checking for Python executable "python" in the PATH
npm ERR! gyp verb `which` failed Error: not found: python
npm ERR! gyp verb `which` failed     at getNotFoundError (C:\Users\USER\Downloads\gatsby-simplefolio-master\node_modules\node-gyp\node_modules\which\which.js:13:12)
npm ERR! gyp verb `which` failed     at F (C:\Users\USER\Downloads\gatsby-simplefolio-master\node_modules\node-gyp\node_modules\which\which.js:68:19)
npm ERR! gyp verb `which` failed     at E (C:\Users\USER\Downloads\gatsby-simplefolio-master\node_modules\node-gyp\node_modules\which\which.js:80:29)
npm ERR! gyp verb `which` failed     at C:\Users\USER\Downloads\gatsby-simplefolio-master\node_modules\node-gyp\node_modules\which\which.js:89:16
npm ERR! gyp verb `which` failed     at C:\Users\USER\Downloads\gatsby-simplefolio-master\node_modules\isexe\index.js:42:5
npm ERR! gyp verb `which` failed     at C:\Users\USER\Downloads\gatsby-simplefolio-master\node_modules\isexe\windows.js:36:5
npm ERR! gyp verb `which` failed     at FSReqCallback.oncomplete (node:fs:191:21)
npm ERR! gyp verb `which` failed  python Error: not found: python
npm ERR! gyp verb `which` failed     at getNotFoundError (C:\Users\USER\Downloads\gatsby-simplefolio-master\node_modules\node-gyp\node_modules\which\which.js:13:12)
npm ERR! gyp verb `which` failed     at F (C:\Users\USER\Downloads\gatsby-simplefolio-master\node_modules\node-gyp\node_modules\which\which.js:68:19)
npm ERR! gyp verb `which` failed     at E (C:\Users\USER\Downloads\gatsby-simplefolio-master\node_modules\node-gyp\node_modules\which\which.js:80:29)
npm ERR! gyp verb `which` failed     at C:\Users\USER\Downloads\gatsby-simplefolio-master\node_modules\node-gyp\node_modules\which\which.js:89:16
npm ERR! gyp verb `which` failed     at C:\Users\USER\Downloads\gatsby-simplefolio-master\node_modules\isexe\index.js:42:5
npm ERR! gyp verb `which` failed     at C:\Users\USER\Downloads\gatsby-simplefolio-master\node_modules\isexe\windows.js:36:5
npm ERR! gyp verb `which` failed     at FSReqCallback.oncomplete (node:fs:191:21) {
npm ERR! gyp verb `which` failed   code: 'ENOENT'
npm ERR! gyp verb `which` failed }
npm ERR! gyp verb could not find "python". checking python launcher
npm ERR! gyp verb could not find "python". guessing location
npm ERR! gyp verb ensuring that file exists: C:\Python27\python.exe
npm ERR! gyp ERR! configure error
npm ERR! gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
npm ERR! gyp ERR! stack     at PythonFinder.failNoPython (C:\Users\USER\Downloads\gatsby-simplefolio-master\node_modules\node-gyp\lib\configure.js:484:19)
npm ERR! gyp ERR! stack     at PythonFinder.<anonymous> (C:\Users\USER\Downloads\gatsby-simplefolio-master\node_modules\node-gyp\lib\configure.js:509:16)
npm ERR! gyp ERR! stack     at callback (C:\Users\USER\Downloads\gatsby-simplefolio-master\node_modules\graceful-fs\polyfills.js:295:20)
npm ERR! gyp ERR! stack     at FSReqCallback.oncomplete (node:fs:191:21)
npm ERR! gyp ERR! System Windows_NT 10.0.19042
npm ERR! gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\USER\\Downloads\\gatsby-simplefolio-master\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
npm ERR! gyp ERR! cwd C:\Users\USER\Downloads\gatsby-simplefolio-master\node_modules\sharp
npm ERR! gyp ERR! node -v v15.2.1
npm ERR! gyp ERR! node-gyp -v v3.8.0
npm ERR! gyp ERR! not ok
npm verb exit 1
npm timing npm Completed in 5128ms

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\USER\AppData\Local\npm-cache\_logs\2021-01-15T06_16_30_238Z-debug.log

USER@LAPTOP-A8RM9C82 MINGW64 ~/Downloads/gatsby-simplefolio-master
$ npm start

> gatsby-starter-hello-world@0.1.0 start
> npm run develop

> gatsby-starter-hello-world@0.1.0 develop
> gatsby develop

npm ERR! path C:\Users\USER\Downloads\gatsby-simplefolio-master
npm ERR! path C:\Users\USER\Downloads\gatsby-simplefolio-master
npm ERR! command failed
npm ERR! signal SIGINT
npm ERR! command C:\WINDOWS\system32\cmd.exe /d /s /c "npm run develop"
npm ERR! command failed
npm ERR! signal SIGINT
npm ERR! command C:\WINDOWS\system32\cmd.exe /d /s /c "gatsby develop"

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\USER\AppData\Local\npm-cache\_logs\2021-01-15T06_19_21_266Z-debug.log

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\USER\AppData\Local\npm-cache\_logs\2021-01-15T06_19_21_260Z-debug.log

**Comment by Mesmerize** [comment]
Ever get this solved? Having same issue
